export const START_LOADING_COURSE = "START_LOADING_COURSE";
export const STOP_LOADING_COURSE = "STOP_LOADING_COURSE";
export const GET_COURSE = "GET_COURSE";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const COURSE_VIEWED = "COURSE_VIEWED";
export const COURSE_VIEWED_SUCCESS = "COURSE_VIEWED_SUCCESS";

export const VIEWED_COURSES = "VIEWED_COURSES";
export const VIEWED_COURSES_SUCCESS = "VIEWED_COURSES_SUCCESS";