export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_FINISHED = "CREATE_COURSE_FINISHED";

export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";

export const EDIT_COURSE = "EDIT_COURSE";
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_FAILED = "EDIT_COURSE_FAILED";

export const CREATE_COURSE_MODULE = "CREATE_COURSE_MODULE";
export const CREATE_COURSE_MODULE_SUCCESS = "CREATE_COURSE_MODULE_SUCCESS";
export const CREATE_COURSE_MODULE_FAILED = "CREATE_COURSE_MODULE_FAILED";

export const DELETE_COURSE_MODULE = "DELETE_COURSE_MODULE";
export const DELETE_COURSE_MODULE_SUCCESS = "DELETE_COURSE_MODULE_SUCCESS";
export const DELETE_COURSE_MODULE_FAILED = "DELETE_COURSE_MODULE_FAILED";

export const EDIT_COURSE_MODULE = "EDIT_COURSE_MODULE";
export const EDIT_COURSE_MODULE_SUCCESS = "EDIT_COURSE_MODULE_SUCCESS";
export const EDIT_COURSE_MODULE_FAILED = "EDIT_COURSE_MODULE_FAILED"