export const START_LOADNG_MODULE = "START_LOADNG_MODULE";
export const STOP_LOADING_MODULE = "STOP_LOADING_MODULE";
export const GET_COURSE_MODULE = "GET_COURSE_MODULE";
export const GET_COURSE_MODULE_SUCCESS = "GET_COURSE_MODULE_SUCCESS";

export const GET_MODULES = "GET_MODULES";
export const GET_MODULES_SUCCESS = "GET_MODULES_SUCCESS";
export const GET_MODULES_FAILED = "GET_MODULES_FAILED";